# generate a template for build.yml
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps

# write a unitest.yml for https://github.com/ChoBioLab/coreSC repository
name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: bash ../../test/test.sh


